###############################
#        Sleepercentage       #
###############################

# A simple module that lets you
# skip nights and storms per
# world, based on a percentage
# of players that are sleeping.

plugin-prefix: "&7[&bSleepercentage&7]"

settings:
  skip-nights: true     # toggles being able to skip nights
  skip-storms: true     # toggles being able to skip storms
  percentage: 50%       # percentage of players needed to skip nights/storms
  sleep-wait: 5         # amount of seconds to wait before skipping nights/storms

  worlds:               # per-world settings for night/storm skips
#    pvp:
#      sleep-wait: 0
#      skip-nights: false
#      skip-storms: true
#      percentage: 30%

